# Praktikum Imbalanced Class

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, roc_curve, auc, f1_score, accuracy_score,confusion_matrix
colnames =['preg','plas','pres','skin','test', 'mass', 'pedi','age','class']
df=pd.read_csv('../resource/diabetes.csv',names=colnames)

In [2]:
df.head()

preg  plas  pres  skin  test  mass     pedi  age  class
0     6   148    72    35     0  33.6  627.000   50      3
1     1    85    66    29     0  26.6  351.000   31      0
2     8   183    64     0     0  23.3  672.000   32      1
3     1    89    66    23    94  28.1  167.000   21      0
4     0   137    40    35   168  43.1    2.288   33      1

In [3]:
X=df.drop('class',axis=1)
y=df['class']


In [4]:
#menghtung jumlah anggota tiap kelas
y.value_counts()

0    500
1    267
3      1
Name: class, dtype: int64

In [5]:
# Split dataset into training set and test set
from sklearn.model_selection import train_test_split # Import train_test_split function
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1) # 70% training and 30% test

# Decision Tree

In [7]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
import sklearn.metrics as metrics
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()
# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
print( '\nClassification report\n' )
print(classification_report(y_test, y_pred))
print( '\nConfusion Matrix\n' )
print(confusion_matrix(y_test, y_pred),'\n')
print('Accuracy :','{:.2f}'.format(accuracy_score(y_test, y_pred)))
print('F-Score :','{:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))
fpr, tpr, thresholds = metrics.roc_curve(y_test, y_pred, pos_label=1)
print('AUC:','{:.2f}'.format(metrics.auc(fpr, tpr)))



Classification report

              precision    recall  f1-score   support

           0       0.74      0.79      0.76        99
           1       0.56      0.50      0.53        54
           3       0.00      0.00      0.00         1

    accuracy                           0.68       154
   macro avg       0.43      0.43      0.43       154
weighted avg       0.67      0.68      0.67       154


Confusion Matrix

[[78 21  0]
 [27 27  0]
 [ 1  0  0]] 

Accuracy : 0.68
F-Score : 0.67
AUC: 0.65


/home/jackshaw/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/jackshaw/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/jackshaw/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# KNN

# NB

In [9]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
# Train Decision Tree Classifer
nb= nb.fit(X_train,y_train)
#Predict the response for test dataset
y_pred= nb.predict(X_test)
print( '\nClassification report\n' )
print(classification_report(y_test, y_pred))
print( '\nConfusion Matrix\n' )
print(confusion_matrix(y_test, y_pred),'\n')
print('Accuracy :','{:.2f}'.format(accuracy_score(y_test, y_pred)))
print('F-Score :','{:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))
fpr, tpr, thresholds = metrics.roc_curve(y_test, y_pred, pos_label=1)
print('AUC:','{:.2f}'.format(metrics.auc(fpr, tpr)))



Classification report

              precision    recall  f1-score   support

           0       0.79      0.85      0.82        99
           1       0.66      0.57      0.61        54
           3       0.00      0.00      0.00         1

    accuracy                           0.75       154
   macro avg       0.48      0.47      0.48       154
weighted avg       0.74      0.75      0.74       154


Confusion Matrix

[[84 15  0]
 [23 31  0]
 [ 0  1  0]] 

Accuracy : 0.75
F-Score : 0.74
AUC: 0.71


/home/jackshaw/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/jackshaw/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/jackshaw/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# SVM

In [11]:
from sklearn.svm import SVC
import warnings
warnings.filterwarnings('ignore')
c_SVC = np.logspace(start = 0, stop = 10, num = 100, base = 2 , dtype = 'float64')
param_grid_S = {'C': c_SVC}
clf_SVC = SVC(C=100.0, kernel='linear', degree=3, gamma='auto', coef0=0.0, shrinking=True, 
          probability=False, tol=0.001, cache_size=200, class_weight=None, 
          verbose=0, max_iter=-1, decision_function_shape="ovr", random_state = 0)
svc=clf_SVC.fit(X_train,y_train)
y_pred= svc.predict(X_test)
print( '\nClassification report\n' )
print(classification_report(y_test, y_pred))
print( '\nConfusion Matrix\n' )
print(confusion_matrix(y_test, y_pred),'\n')
print('Accuracy :','{:.2f}'.format(accuracy_score(y_test, y_pred)))
print('F-Score :','{:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))
fpr, tpr, thresholds = metrics.roc_curve(y_test, y_pred, pos_label=1)
print('AUC:','{:.2f}'.format(metrics.auc(fpr, tpr)))


Classification report

              precision    recall  f1-score   support

           0       0.81      0.84      0.83        99
           1       0.67      0.65      0.66        54
           3       0.00      0.00      0.00         1

    accuracy                           0.77       154
   macro avg       0.50      0.50      0.50       154
weighted avg       0.76      0.77      0.76       154


Confusion Matrix

[[83 16  0]
 [19 35  0]
 [ 0  1  0]] 

Accuracy : 0.77
F-Score : 0.76
AUC: 0.74


# Random Forest

In [12]:
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier (n_estimators=100,random_state=0)
rf= rf.fit(X_train, y_train)
y_pred= rf.predict(X_test)
print( '\nClassification report\n' )
print(classification_report(y_test, y_pred))
print( '\nConfusion Matrix\n' )
print(confusion_matrix(y_test, y_pred),'\n')
print('Accuracy :','{:.2f}'.format(accuracy_score(y_test, y_pred)))
print('F-Score :','{:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))
fpr, tpr, thresholds = metrics.roc_curve(y_test, y_pred, pos_label=1)
print('AUC:','{:.2f}'.format(metrics.auc(fpr, tpr)))


Classification report

              precision    recall  f1-score   support

           0       0.83      0.84      0.83        99
           1       0.69      0.69      0.69        54
           3       0.00      0.00      0.00         1

    accuracy                           0.78       154
   macro avg       0.51      0.51      0.51       154
weighted avg       0.77      0.78      0.78       154


Confusion Matrix

[[83 16  0]
 [17 37  0]
 [ 0  1  0]] 

Accuracy : 0.78
F-Score : 0.78
AUC: 0.76


# Regresi Logistic

In [13]:
from sklearn.linear_model import LogisticRegression
rf = LogisticRegression(random_state=0)
rf= rf.fit(X_train, y_train)
y_pred= rf.predict(X_test)
print( '\nClassification report\n' )
print(classification_report(y_test, y_pred))
print( '\nConfusion Matrix\n' )
print(confusion_matrix(y_test, y_pred),'\n')
print('Accuracy :','{:.2f}'.format(accuracy_score(y_test, y_pred)))
print('F-Score :','{:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))
fpr, tpr, thresholds = metrics.roc_curve(y_test, y_pred, pos_label=1)
print('AUC:','{:.2f}'.format(metrics.auc(fpr, tpr)))


Classification report

              precision    recall  f1-score   support

           0       0.69      0.88      0.77        99
           1       0.56      0.28      0.37        54
           3       0.00      0.00      0.00         1

    accuracy                           0.66       154
   macro avg       0.41      0.39      0.38       154
weighted avg       0.64      0.66      0.62       154


Confusion Matrix

[[87 12  0]
 [39 15  0]
 [ 1  0  0]] 

Accuracy : 0.66
F-Score : 0.62
AUC: 0.58
